# Generated by Django 4.1.5 on 2023-01-30 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
